lib/ImportDefinitions/Plugin.php

Plugin is accessible, routine fails with a MySQL statement: Mysqli prepare error: Table 'mysql.importdefinitions_log' doesn't exist

Table importdefinitions_log is not generated at install

---

static/js/definition/item.js

I noticed that if you do NOT use strict searching and have multiple columns that start with the same string, they may return the wrong record. Example, field collection with a text input field "size_parent_sku" and a combo called "size". When viewing the fields in the import definition, size is not displayed, and in its place is size_parent_sku. I believe this only happens if the size field is below the size_parent_sku field. Implementing strict searching prevents this.

Implemented strict searching to .findRecord

---

src/ImportDefinitionsBundle/Resources/public/pimcore/js/definition/configDialog.js

Fix:
- window with formpanel is rendered in the _pimcore_body_ element after selecting dropdown's value in the grid column

Added config renderTo for Window

---

src/ImportDefinitionsBundle/Resources/public/pimcore/js/definition/item.js

findRecord finds the first matching Record in this store by a specific field value. It leads to wrong results in case if store has values which have similar part of string.
Example of store values:
testAAAA
testAA
test
testAAAA will be returned on any of those string searching, because it is first in the store

fix: findRecord for fromColumn and toColumn store data

---

src/ImportDefinitionsBundle/Resources/public/pimcore/js/definition/item.js

Problem:
On newly created definition, when provider is selected an error message is displayed. This prevents provider settings and mapping tabs to be reloaded - whole definition has to be closed and opened again.
This PR fixes that.

Fixes error on selecting provider in newly created definition.

---

src/ImportDefinitionsBundle/Resources/public/pimcore/js/definition/configDialog.js

This allows usage of drag & drop in interpreters and setter.
Also, windows with modal = true are rendered very slowly.

Sets modal = false on configDialog window.

---

src/ImportDefinitionsBundle/Controller/DefinitionController.php

This enables system columns to be primary identifiers too. Only thing that would change is setting the parent, it's now expecting a ID instead of a DataObject.

Changed system columns

---

src/ImportDefinitionsBundle/Importer/Importer.php

Assuming `name=Foo Bar bla 123 / 456`
When importing with settings key set to `%Text(name);`, import process would normalize to "foo-bar-bla-123-456", admin would normalize to "Foo Bar bla 123 - 456". This streamlines the outcome.

fix: normalize the key the same way admin does

---

src/ImportDefinitionsBundle/Provider/XmlProvider.php
src/ImportDefinitionsBundle/Resources/public/pimcore/js/provider/xml.js

When a user tries to save ImportDefinition settings for import from XML file the error occurs:
`configuration: This form should not contain extra fields.`
Moreover during a process of import no data if read from XML (error about missing XPath).
This pull request solves those problems.

Fix problem with xPath

---

src/ImportDefinitionsBundle/ProcessManager/ImportDefinitionsReport.php
src/ImportDefinitionsBundle/ProcessManager/ProcessManagerListener.php
src/ImportDefinitionsBundle/Resources/config/process_manager.yml

I see that 'object start' and 'object finished' avent are being triggered, but they duplicate status event. So I'have added finished event handling only.

added finished event handling

---

src/ImportDefinitionsBundle/Importer/Importer.php
src/ImportDefinitionsBundle/Runner/SaveRunnerInterface.php

Added SaveRunnerInterface that allow the runner to perform extra validation and prevent the object from being saved.
In our project we use it like below to create a runner that only saves the object when there are changes to the data. This way we do not get any versions of the object that does not have changes. Makes the object history MUCH cleaner.
```
namespace Caupo\IntegrationBundle\Runner;
use Pimcore\Model\DataObject\Concrete;
use ImportDefinitionsBundle\Model\DefinitionInterface;
use ImportDefinitionsBundle\Model\Mapping;
use ImportDefinitionsBundle\Runner\SaveRunnerInterface;
use ImportDefinitionsBundle\Runner\SetterRunnerInterface;
class SkipNotModifiedRunner implements SaveRunnerInterface, SetterRunnerInterface
{
private $hasChanges;
public function preRun(Concrete $object, …
```

Added SaveRunnerInterface

---

src/ImportDefinitionsBundle/DependencyInjection/Configuration.php

A tiny one... the js file for  reverse interpreter iterator was never added to the configuration so it was not loaded

Add missing reverse interprerter iterator js to configuration

---

src/ImportDefinitionsBundle/Controller/ExportDefinitionController.php

Adds 'children' as a system field for exports. My primary use case is to include the sku of child products/variants of a 'configurable' product. The change is as simple as adding 'children' to the system fields array in ExportDefinitionController. The getter getChildren already exist and returns an array that can be handled with an Iterator-interpreter or soemthing like it.

Add 'children' as system field for exports

---

src/ImportDefinitionsBundle/Importer/Importer.php

PHP Errors cause Imports to stop without logging anything for user (e.g. in Process Manager). Single-line errors break whole imports. This is especially annoying when users try to debug their mapping (most often it's a type error).
By catching Throwable instead of Exception, the import won't stop and additional info will be logged.

Catch all errors during import.

---

src/ImportDefinitionsBundle/Controller/ExportDefinitionController.php
src/ImportDefinitionsBundle/Controller/ImportDefinitionController.php
src/ImportDefinitionsBundle/Resources/public/pimcore/js/getters/classificationstore.js
src/ImportDefinitionsBundle/Resources/public/pimcore/js/setters/classificationstore.js

| Fixed tickets | #131
this comes directly from the controller

Remove field configuration for classification store in Getter

---

src/ImportDefinitionsBundle/Provider/XmlProvider.php

The unused variable. It triggers a bug if you have a collection of collections of properties.

fix: drop unused variable in XmlProvider::serializeCollection

---

src/ImportDefinitionsBundle/Interpreter/IteratorInterpreter.php

Passing `NULL` to the iterator just returns an empty array, it's not a hard error anymore.

fix: allow NULL to be passed to IteratorInterpreter

---

src/ImportDefinitionsBundle/Controller/ExportDefinitionController.php

In export definition edit there was no `published` field to be selected in a system fields list. This disallows to export it and a user was unable to implement soft-delete based on that column value in the export file.

feature: add published field to export system fields list

---

src/ImportDefinitionsBundle/Resources/public/pimcore/js/export/fields.js

If I want export objects from a class which has only translateable fields, the mapping tab is empty.

Fix: No mapping if class has only translateable fields

---

src/ImportDefinitionsBundle/Provider/AbstractFileProvider.php
src/ImportDefinitionsBundle/Provider/CsvProvider.php
src/ImportDefinitionsBundle/Provider/ExcelProvider.php
src/ImportDefinitionsBundle/Provider/JsonProvider.php
src/ImportDefinitionsBundle/Provider/XmlProvider.php

In the moment it is impossible to execute impots or exports with a absoulte file path
`php bin/console import-definitions:import -d 1 -p '{"file":"\/tmp\/migration.json"}'`

Execute imports and exports with absolute file path

---

src/ImportDefinitionsBundle/Provider/ExcelProvider.php

With empty trailing cells, ExcelProvider will truncate the row array to remove all trailing empty cells. This doesn't allow array_combine to work. This re-aligns the row to the headers by padding the array or removing the overflow should it happen.

fix: make sure ExcelProvider combines the headers with row

---

src/ImportDefinitionsBundle/Fetcher/ObjectsFetcher.php

Applying `UnpublishedHelper::hideUnpublished()` is too late, it will have already counted only the published items.
This will cause a weird scenario where Pimcore thinks there are X items (published + unpublished), Exporter will say there are Y (published only), will then try to export MORE items, but only up to a number Z divisible by 50.

fix: properly COUNT(*) unpublished items

---

src/ImportDefinitionsBundle/Command/AbstractImportDefinitionCommand.php
src/ImportDefinitionsBundle/Resources/config/services/commands.yml

| Fixed tickets | #...   
`import-definition:definition:import` and  `export-definition:definition:import`
@blankse We have to change the names again, since the currents interfere with currently used shortcurts like `im:im`

change command for definitions:import

---

src/ImportDefinitionsBundle/Interpreter/MultiHrefInterpreter.php
src/ImportDefinitionsBundle/Interpreter/ObjectResolverInterpreter.php

When using the `ObjectResolverInterpreter` the importer will fail on case sensitive file systems. The following fatal error is thrown:
`Error: Class 'Pimcore\Model\DataObject\brand' not found in vendor/w-vision/import-definitions/src/ImportDefinitionsBundle/Interpreter/ObjectResolverInterpreter.php:38`
This is caused by PHP not able to find the class. The FQCN should be `Pimcore\Model\DataObject\Brand` to be able to load correctly.
I checked the pimcore core code and found several occasions where Pimcore also uppercases the first character to resolve this issue. So this should be the right solution.

Fix issue with case sensitive filesystems.

---

src/ImportDefinitionsBundle/Exporter/Exporter.php
src/ImportDefinitionsBundle/Getter/DynamicColumnGetterInterface.php

It allows a getter to return multiple (or none) columns instead of just
the one, allowing for dynamic column names, order, etc.

feature: dynamic column getter interface

---

src/ImportDefinitionsBundle/Importer/Importer.php

| BC breaks?    | maybe?
| Fixed tickets | #190 partially
If the dataset is missing a column instead of setting null to target field it will be skipped.

If column is missing in dataset, null value will not be imported.

---

src/ImportDefinitionsBundle/Importer/Importer.php

My recent PR #191 introduced this problem - if we're using "Custom" as a fromColumn mapping, it won't be processed. This PR should fix this.

Fix for Custom column mapping

---

src/DataDefinitionsBundle/Form/Type/Interpreter/CarbonInterpreterType.php
src/DataDefinitionsBundle/Interpreter/CarbonInterpreter.php
src/DataDefinitionsBundle/Resources/config/pimcore/config.yml
src/DataDefinitionsBundle/Resources/config/services.yml
src/DataDefinitionsBundle/Resources/public/pimcore/js/interpreters/carbon.js

Q | A
-- | --
Bug fix? | no
New feature? | yes
BC breaks? | no
Deprecations? | no
Add possibility to define a custom date format in the Carbon interpreter, so we can use arbitrary dates while importing.

Implement configurable date format for carbon interpreter

---

src/DataDefinitionsBundle/ProcessManager/ImportDefinitionsReport.php

Information about an error is saved in array but not in `productStatus` key. Because of that in the report, we don't have information about errors.

fix / Show errors in report

---

src/DataDefinitionsBundle/DependencyInjection/DataDefinitionsExtension.php
src/DataDefinitionsBundle/Form/Type/Interpreter/CoreShop/MoneyInterpreterType.php
src/DataDefinitionsBundle/Interpreter/CoreShop/MoneyInterpreter.php
src/DataDefinitionsBundle/Resources/config/coreshop.yml
src/DataDefinitionsBundle/Resources/public/pimcore/js/coreshop/interpreter/money.js

| Fixed tickets | -
If a currency code is in the import value, the currency object is searched for via the repository. If no currency is found, the currency of the configuration is returned.

[Interpreter] Added CoreShop Money interpreter

---

src/DataDefinitionsBundle/Provider/CsvProvider.php

As importing supports iterators, there is no point in returning array here.
For tested 70MB CSV file this lowers the memory consumption at import start from >1GB to 40MB

CsvProvider's getData can return iterator

---

src/DataDefinitionsBundle/Interpreter/AssetUrlInterpreter.php
src/DataDefinitionsBundle/Resources/config/services.yml

| Fixed tickets | #224 
AssetUrl Interpreter uses file_get_contents to download file. If Pimcore instance is using proxy to communicate with the Internet - it won't work.
Fix: use Pimcore's HttpClient to download data.

Using Pimcore's HttpClient to download data

---

src/DataDefinitionsBundle/Form/Type/Interpreter/MetadataInterpreterType.php
src/DataDefinitionsBundle/Interpreter/MetadataInterpreter.php
src/DataDefinitionsBundle/Resources/config/pimcore/config.yml
src/DataDefinitionsBundle/Resources/config/services.yml
src/DataDefinitionsBundle/Resources/public/pimcore/js/interpreters/metadata.js
src/DataDefinitionsBundle/Setter/KeySetter.php
src/DataDefinitionsBundle/Setter/RelationSetter.php

A small bug fix for the KeySetter. It was not possible to use it on system fields like o_key. It would try to use a setter setO_key.
Added a Metadata interpreter. Before it was not possible to import data to advanced relation fields since those expect ObjectMetadata or ElementMetadata, not Elements. This interpreter fixes that by wrapping the value in one of the Metadata classes. Which class to use is a configuration option in the interpreter. Which one is needed depends on the target relation. There is also a configuration option to add a json string that will be used as metadata for your element. This would typically be used nested with a Asset or …

KeySetter bugfix and Advanced Relations interpreter/setter

---

src/DataDefinitionsBundle/Command/ExportCommand.php
src/DataDefinitionsBundle/Exporter/Exporter.php

| Fixed tickets | #237 
This ensures the export process always runs fully, even with zero results, creating an empty artifact where expected.
Closes #237 .

fix: run the export process even with zero items

---

src/DataDefinitionsBundle/Form/Type/ExportDefinitionType.php
src/DataDefinitionsBundle/Form/Type/ExportProviderChoiceType.php
src/DataDefinitionsBundle/Form/Type/ImportDefinitionType.php
src/DataDefinitionsBundle/Form/Type/ImportProviderChoiceType.php
src/DataDefinitionsBundle/Resources/config/services/forms.yml

| Fixed tickets | #238 
Providers injections into import/export form types instead of using the common custom select

Separate import and export providers in select field

---

src/DataDefinitionsBundle/Setter/FieldCollectionSetter.php

There is only 3 parameters in the config array, "fieldcollectionField" and "fieldcollectionKeys" does not exist but "field" and "keys" exist. and now it work. (thx for your work)

Fix config keys for fieldcollection setter

---

src/DataDefinitionsBundle/Interpreter/InterpreterInterface.php

The parameter `$map` of method `...::interpret()` has invalid typehint type `Wvision\Bundle\DataDefinitionsBundle\Interpreter\Mapping`.

Invalid typehint type Mapping on InterpreterInterface

---

src/DataDefinitionsBundle/Importer/Importer.php

Added new events that allow performing additional actions when import process is finished successfully or with errors. For example - we can delete an asset, or move it another folder.

Success and Failure events.

---

src/DataDefinitionsBundle/Command/ImportCommand.php
src/DataDefinitionsBundle/Importer/Importer.php
src/DataDefinitionsBundle/ProcessManager/ImportDefinitionProcess.php

This PR allows setting `userId` parameter to an import. It will be used then to mark modificationUser of an object. 
This could be useful if importer is used in an integration - e.g. we can mark user as `erp`.
Also if import was started using Process Manager - current user will be set.

Added possibility to set user for an import.

---

src/DataDefinitionsBundle/Interpreter/CheckboxInterpreter.php
src/DataDefinitionsBundle/Interpreter/DoNotSetOnEmptyInterpreter.php
src/DataDefinitionsBundle/Resources/config/services.yml

Interpreter that will cause DoNotSetException if passed value is empty. Can be chained in nested interpreter to break interpretation or as in my case - do not change the the checkbox to false (or null) if the value is empty.
To achieve the latter, a change was also needed in checkbox interpreter. `filter_var` with used flags returned false on empty string.
| BC breaks?    | yes

DoNotSetOnEmptyInterpreter.

---

src/DataDefinitionsBundle/ProcessManager/AbstractProcessManagerListener.php

The `$process` variable is undefined, so we have to use `$this->process` here.

[AbstractProcessManagerListener] Use correct variables

---

src/DataDefinitionsBundle/Interpreter/AssetUrlInterpreter.php

| Fixed tickets | -
In some cases `$listing->current()` is returning a boolean value which triggers an error because of the type hinting.

Fix 'getDuplicatedAsset' returning boolean values

---

src/DataDefinitionsBundle/Resources/public/pimcore/js/interpreters/mapping.js

Fixed "Null when not found" checkbox in import definitions mapping interpreter. 
Previously it wouldn't save and always evaluate to false.

Fix mapping interpreter checkbox

---

src/DataDefinitionsBundle/Resources/config/services/commands.yml

| Deprecations? | yes
I was getting errors about the coreshop.resource_registry service not being public. Noticed it is deprecated in the Coreshop Resource bundle. So I replaced the alias in the service definition for the import/export commands.

Don't use deprecated alias 'coreshop.resource_registry'

---

src/DataDefinitionsBundle/Fetcher/ObjectsFetcher.php
src/DataDefinitionsBundle/ProcessManager/ProcessManagerExportListener.php

If doing pagination, the order is important since you're relying on it being stable across pages to actually walk through the intended dataset.
If the ORDER BY is not specified, the actual order is undefined, meaning you can get pages skipped and duplicated. It will mostly work because the same order is kept, but sometimes it might fail (as in my case, on MariaDB 10). The issue is, it didn't always fail, only sometimes (on some pages), being totally unpredictable and requiring a large amount of debugging.

fix: ensure a stable sort across pages + artifact regression

---

src/DataDefinitionsBundle/Setter/RelationSetter.php

| Fixed tickets |
In the relation setter the value is assumed to be either a single data object or an array of objects. By using `is_iterable` instead of `is_array` we can allow any type of iterable for example a `Listing`.

Allow any iterable type on value rather than only arrays

---

src/DataDefinitionsBundle/Form/Type/Interpreter/MultiHrefInterpreterType.php

| Fixed tickets | #...   
Field `type` is missing in FormType causing `This form should not contain extra fields.`
Extend `HrefInterpreter` form type, as it happens for the ExtJS part, since the configurations are the same.

Fix error when saving a configuration for MultiHrefInterpreter

---

src/DataDefinitionsBundle/Interpreter/QuantityValueInterpreter.php

If passing an empty string to QuantityValue in a Classification store, it will be interpreted as 0, but should be as a `null`.
See https://github.com/pimcore/pimcore/issues/8277 for another related issue.

fix: interpret passing an empty string to QuantityValue as null

---

src/DataDefinitionsBundle/Importer/Importer.php
src/DataDefinitionsBundle/Resources/config/services.yml

Added support for Pimcore model class overrides (see: https://pimcore.com/docs/pimcore/current/Development_Documentation/Extending_Pimcore/Overriding_Models.html)
Currently the Importer always instantiates a default model (`Pimcore\Model\DataObject\...`) instead of checking if there is an override configured (i.e. `App\Model\DataObject\...`).

Support for class overrides

---

src/DataDefinitionsBundle/ProcessManager/ExportDefinitionProcess.php
src/DataDefinitionsBundle/ProcessManager/ImportDefinitionProcess.php

| Fixed tickets | https://github.com/dpfaffenbauer/ProcessManager/pull/59
Correctly passes the arguments with the BC break in Pimcore.

fix: latest change in ProcessManager, change args passing

---

src/DataDefinitionsBundle/Importer/Importer.php
src/DataDefinitionsBundle/Provider/TraversableImportDataSet.php

| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Branch?          | master
In Importer.php the event "data_definitions.import.total" never gets get dispatched when $data is an object of type \Wvision\Bundle\DataDefinitionsBundle\Provider\TraversableImportDataSet.
Fixed this by adding Countable interface and setting the count on object creation.

Event "data_definitions.import.total" never gets dispatched

---

src/DataDefinitionsBundle/ProcessManager/AbstractProcessManagerListener.php
src/DataDefinitionsBundle/ProcessManager/ProcessManagerExportListener.php

| Fixed tickets | #331
We introduced a tweak which stops the status event being dispatched too often, but this has two side-effects with the progress bar in Process manager:
1. it doesn't update correctly
2. it never reaches 100%
This fixes both issues.

fix: properly account for progress steps when throttling status

---

src/DataDefinitionsBundle/Provider/XmlProvider.php

Using copy() + unlink() instead

fix: XML Provider export rename() not friendly to streams

---

src/DataDefinitionsBundle/Provider/ExcelProvider.php

This is the same fix as #357 just for ExcelProvider this time

fix: excel provider export rename() not friendly to streams

---

src/DataDefinitionsBundle/Setter/ClassificationStoreSetter.php

| Deprecations? | yes/no
| Fixed tickets | N(A

fix: ClassificationStoreSetter doesn't handle empty groups correctly
