w-vision/DataDefinitions

- lib/ImportDefinitions/Model/Interpreter/Href.php
should fix the #37 issue according class name in $class
> fix #37 class name could have first letter in uppercase

- README.md
- src/ImportDefinitionsBundle/ImportDefinitionsBundle.php
will be merged as soon as CoreShop Beta-1 comes out
> Use DependantBundle that will be introduced in beta-1 from coreshop-resource-bundle

- src/ImportDefinitionsBundle/Interpreter/AssetUrlInterpreter.php
- src/ImportDefinitionsBundle/PlaceholderContext.php
- src/ImportDefinitionsBundle/Service/Placeholder.php
This can be used to use the current object's path as the path of
imported assets, for example.
> feature: embed the current object into placeholder params

- src/ImportDefinitionsBundle/Resources/public/pimcore/js/process_manager/import_definitions.js
Added "find" and "upload" functionality in new/edit executable dialog window.
> Easy use of files in ImportDefinition executable editing

- src/ImportDefinitionsBundle/DependencyInjection/Configuration.php
- src/ImportDefinitionsBundle/Form/Type/Interpreter/IteratorInterpreterType.php
- src/ImportDefinitionsBundle/Interpreter/IteratorInterpreter.php
- src/ImportDefinitionsBundle/Resources/config/services.yml
- src/ImportDefinitionsBundle/Resources/public/pimcore/js/interpreters/iterator.js
adds a new iterator type to handle array values more elegant.
related to #76 
@dkarlovi can you test it please?
> feature: iterator-type

- src/ImportDefinitionsBundle/Form/Type/Interpreter/AssetUrlInterpreterType.php
- src/ImportDefinitionsBundle/Form/Type/Interpreter/AssetsUrlInterpreterType.php
- src/ImportDefinitionsBundle/Interpreter/AssetUrlInterpreter.php
- src/ImportDefinitionsBundle/Resources/public/pimcore/js/interpreters/asseturl.js
> feature: support to relocate/rename assets deduplicated by origin URL

- src/ImportDefinitionsBundle/Provider/XmlProvider.php
- src/ImportDefinitionsBundle/Resources/config/services.yml
> feature: XML Exports support

- src/ImportDefinitionsBundle/Resources/public/pimcore/js/interpreters/nestedcontainer.js
> Fixed issue with sorting nested interpreter items

- src/ImportDefinitionsBundle/Controller/ExportDefinitionController.php
- src/ImportDefinitionsBundle/Resources/public/pimcore/js/export/configDialog.js
- src/ImportDefinitionsBundle/Resources/public/pimcore/js/getters/classificationstore.js
- src/ImportDefinitionsBundle/Resources/public/pimcore/js/getters/fieldcollection.js
- src/ImportDefinitionsBundle/Setter/ClassificationStoreSetter.php
> fixes for classification store getter

- src/ImportDefinitionsBundle/Exporter/Exporter.php
- src/ImportDefinitionsBundle/Fetcher/ObjectsFetcher.php
- src/ImportDefinitionsBundle/Form/Type/ExportDefinitionType.php
- src/ImportDefinitionsBundle/Model/ExportDefinition.php
- src/ImportDefinitionsBundle/Model/ExportDefinition/Dao.php
- src/ImportDefinitionsBundle/Model/ExportDefinitionInterface.php
- src/ImportDefinitionsBundle/Resources/config/serializer/Model.ExportDefinition.yml
- src/ImportDefinitionsBundle/Resources/public/pimcore/js/export/item.js
> Fetcher unpublished relations

- src/ImportDefinitionsBundle/Controller/ExportDefinitionController.php
- src/ImportDefinitionsBundle/Resources/config/services.yml
- src/ImportDefinitionsBundle/Setter/ClassificationStoreFieldGetter.php
> allow to export a classification store at once

- src/ImportDefinitionsBundle/Provider/ExternalSqlProvider.php
> Fix driver setting in ExternalSqlProvider

- src/ImportDefinitionsBundle/Importer/Importer.php
- src/ImportDefinitionsBundle/Provider/ImportDataSet.php
- src/ImportDefinitionsBundle/Provider/ImportDataSetInterface.php
- src/ImportDefinitionsBundle/Provider/ProviderInterface.php
> changed interfaces and CsvProvider implementation

- etc/_config/system.template.php
- src/ImportDefinitionsBundle/Provider/AbstractSqlProvider.php
- src/ImportDefinitionsBundle/Resources/public/pimcore/js/provider/externalSql.js
Fetch just one row for mappings.
'pdo_mysql' driver needs to be in lowercase apparently.
> SQL Provider fixes

- src/ImportDefinitionsBundle/Interpreter/AssetUrlInterpreter.php
| Fixed tickets | #160 
Closes #160.
> feature: try to lookup asset by Pimcore's own asset URL

- src/ImportDefinitionsBundle/Interpreter/AssetUrlInterpreter.php
> fix: correctly lookup by original URL after having tried Pimcore URL

- src/ImportDefinitionsBundle/Interpreter/CarbonInterpreter.php
- src/ImportDefinitionsBundle/Resources/config/services.yml
| Fixed tickets |
Date Fields needs Carbon as value
> Carbon Interpreter

- src/ImportDefinitionsBundle/Provider/ExcelProvider.php
> fix: cast objects (like DataObject or Asset) to string

- src/ImportDefinitionsBundle/Command/ExportCommand.php
- src/ImportDefinitionsBundle/Command/ImportCommand.php
- src/ImportDefinitionsBundle/DependencyInjection/Configuration.php
- src/ImportDefinitionsBundle/Model/AbstractDataDefinition.php
- src/ImportDefinitionsBundle/Repository.php
I needs to execute the export and import command by name
> Execute imports and exports by name

- src/ImportDefinitionsBundle/Interpreter/CheckboxInterpreter.php
Strtolower on $value, so it can handle uppercase values like "True" or "FALSE"
| BC breaks?    | somewhat
> Fix for checkbox interpreter.

- src/DataDefinitionsBundle/Command/ExportCommand.php
- src/DataDefinitionsBundle/Command/ImportCommand.php
- src/DataDefinitionsBundle/Command/ListExportDefinitionsCommand.php
- src/DataDefinitionsBundle/Event/ExportDefinitionEvent.php
- src/DataDefinitionsBundle/Exporter/Exporter.php
- src/DataDefinitionsBundle/Exporter/ExporterInterface.php
- src/DataDefinitionsBundle/Fetcher/FetcherInterface.php
- src/DataDefinitionsBundle/Fetcher/ObjectsFetcher.php
- src/DataDefinitionsBundle/Getter/DynamicColumnGetterInterface.php
- src/DataDefinitionsBundle/Importer/Importer.php
- src/DataDefinitionsBundle/ProcessManager/ArtifactGenerationProviderInterface.php
- src/DataDefinitionsBundle/ProcessManager/ArtifactProviderTrait.php
- src/DataDefinitionsBundle/ProcessManager/ImportDefinitionsReport.php
- src/DataDefinitionsBundle/Provider/CsvProvider.php
- src/DataDefinitionsBundle/Provider/ExcelProvider.php
- src/DataDefinitionsBundle/Provider/ExportProviderInterface.php
- src/DataDefinitionsBundle/Provider/JsonProvider.php
- src/DataDefinitionsBundle/Provider/XmlProvider.php
- src/DataDefinitionsBundle/Resources/config/coreshop.yml
- src/DataDefinitionsBundle/Resources/config/process_manager.yml
- src/DataDefinitionsBundle/Resources/config/services.yml
- src/DataDefinitionsBundle/Resources/config/services/forms.yml
- src/DataDefinitionsBundle/Resources/public/pimcore/js/interpreters/definition.js
- src/DataDefinitionsBundle/Resources/public/pimcore/js/resource/definition.js
- src/DataDefinitionsBundle/Runner/ExportRunnerInterface.php
by fixing exports and removing services aliases to import_definition and rename events for data_definitions
> further prepare 3.0 release 

- src/DataDefinitionsBundle/DependencyInjection/DataDefinitionsExtension.php
- src/DataDefinitionsBundle/Fetcher/ObjectsFetcher.php
- src/DataDefinitionsBundle/Form/Type/ProcessManager/ExportDefinitionObjectStartupForm.php
- src/DataDefinitionsBundle/Resources/public/pimcore/js/process_manager/export_contextmenu.js
- src/DataDefinitionsBundle/Resources/public/pimcore/js/process_manager/export_search.js
> feature: add support to start an export from the folder search grid

- src/DataDefinitionsBundle/Provider/XmlProvider.php
Fixes #229.
| Fixed tickets | #229
> fix: avoid the xsltproc idle timeout by Symfony Process

- src/DataDefinitionsBundle/Resources/public/pimcore/js/process_manager/export_definitions.js
- src/DataDefinitionsBundle/Resources/public/pimcore/js/process_manager/import_definitions.js
Fixes some bugs, which are caused by https://github.com/pimcore/pimcore/pull/5222
> fix: replace jQuery with Vanilla JS

- src/DataDefinitionsBundle/Exception/UnexpectedValueException.php
- src/DataDefinitionsBundle/Exporter/Exporter.php
- src/DataDefinitionsBundle/Importer/Importer.php
> [Logging] allow to inject logger into Interpreter/Cleaner/Runner and Filter

- src/DataDefinitionsBundle/Controller/ExportDefinitionController.php
- src/DataDefinitionsBundle/Resources/config/services.yml
- src/DataDefinitionsBundle/Resources/public/pimcore/js/export/fields.js
- src/DataDefinitionsBundle/Resources/public/pimcore/js/getters/objectbrick.js
> fix export brick getters

- src/DataDefinitionsBundle/Interpreter/AssetUrlInterpreter.php
This PR allows to get filename for urls like `https://etim.one/product-card/pdf/4969194-plstL9FKhOBsmnkyMV3n5I6/lang/pl` - instead of interpreting it as `pl` and possibly causing duplicate key errors, it will take filename from Content-Disposition headers (if set).
> Take filename from Content-Disposition

- docs/interpreter.md
Short, technical description of what each interpreter does.
I'm not sure how Metadata works...
> Docs for interpreters.

- src/DataDefinitionsBundle/Interpreter/ImportRuleInterpreter.php
- src/DataDefinitionsBundle/Resources/config/pimcore/config.yml
- src/DataDefinitionsBundle/Resources/config/services/import_rules.yml
- src/DataDefinitionsBundle/Resources/public/pimcore/js/import_rule/actions/object.js
- src/DataDefinitionsBundle/Resources/public/pimcore/js/import_rule/item.js
- src/DataDefinitionsBundle/Resources/public/pimcore/js/import_rule/panel.js
- src/DataDefinitionsBundle/Rules/Action/ExpressionProcessor.php
- src/DataDefinitionsBundle/Rules/Action/ImportRuleProcessorInterface.php
- src/DataDefinitionsBundle/Rules/Action/ObjectProcessor.php
- src/DataDefinitionsBundle/Rules/Condition/AbstractConditionChecker.php
- src/DataDefinitionsBundle/Rules/Condition/ExpressionConditionChecker.php
- src/DataDefinitionsBundle/Rules/Form/Type/Action/ExpressionType.php
- src/DataDefinitionsBundle/Rules/Form/Type/Action/ObjectType.php
- src/DataDefinitionsBundle/Rules/Processor/ImportRuleValidationProcessor.php
- src/DataDefinitionsBundle/Rules/Processor/RuleApplier.php
- src/DataDefinitionsBundle/Rules/Processor/RuleApplierInterface.php
| Bug fix?      | yes/no
| New feature?  | yes/no
| Deprecations? | yes/no
| Fixed tickets | #...
> [ImportRules] v2 changes

- src/DataDefinitionsBundle/Importer/Importer.php
> Add missing method arguments to call

- src/DataDefinitionsBundle/Controller/ImportRuleController.php
> Fix import of ImportRules

- src/DataDefinitionsBundle/Controller/ImportRuleController.php
> strtolower active for import rule import

- features/interpreter/external_image.feature
- features/interpreter/link.feature
- src/DataDefinitionsBundle/Interpreter/ExternalImageInterpreter.php
- src/DataDefinitionsBundle/Interpreter/LinkInterpreter.php
- src/DataDefinitionsBundle/Resources/config/services.yml
- tests/DataDefinitionsBundle/Behat/Context/Domain/PimcoreContext.php
- tests/DataDefinitionsBundle/Behat/Context/Setup/PimcoreClassContext.php
> introduce link and external image interpreter

- src/DataDefinitionsBundle/Interpreter/LinkInterpreter.php
| Bug fix?      |no
| New feature?  |no
>  LinkInterpreter: set text as value

- docs/interpreter.md
| Fixed tickets | #...   
Fix typos in Interpreter docs
> Fix typos in Interpreter docs

- src/DataDefinitionsBundle/ProcessManager/ImportDefinitionProcess.php
> Fix "warning: creating default object from empty value"

- src/DataDefinitionsBundle/Exception/InterpreterException.php
- src/DataDefinitionsBundle/Importer/Importer.php
- src/DataDefinitionsBundle/Installer.php
> [PimcoreX] fixes

- .github/workflows/behat.yml
- .github/workflows/static.yml
- src/DataDefinitionsBundle/Importer/Importer.php
- src/DataDefinitionsBundle/Provider/ExcelProvider.php
> Fix ExcelProvider

- src/DataDefinitionsBundle/ProcessManager/AbstractProcessManagerListener.php
| Fixed tickets | https://github.com/dpfaffenbauer/ProcessManager/issues/58
> fix: progress updates getting dispatched too often

- src/DataDefinitionsBundle/Model/DataSetAwareInterface.php
- src/DataDefinitionsBundle/Model/DataSetAwareTrait.php
- src/DataDefinitionsBundle/ProcessManager/ArtifactProviderTrait.php
- src/DataDefinitionsBundle/Provider/ExcelProvider.php
| BC breaks?    | yes
| Fixed tickets | -
Fixing some issues with `uninitialized` typed properties which coused troubles within our application. There are probably a lot more of those as mentioned in #336.
> fixes for some uninitialized typed properties

- src/DataDefinitionsBundle/ProcessManager/AbstractProcessManagerListener.php
- src/DataDefinitionsBundle/ProcessManager/ArtifactProviderTrait.php
- src/DataDefinitionsBundle/ProcessManager/ProcessManagerExportListener.php
- src/DataDefinitionsBundle/Provider/JsonProvider.php
- src/DataDefinitionsBundle/Provider/XmlProvider.php
- src/DataDefinitionsBundle/Resources/public/pimcore/js/process_manager/import_definitions.js
| Fixed tickets | NA
Replaces #340.
> Sigwin fixes

- src/DataDefinitionsBundle/Interpreter/AssetUrlInterpreter.php
| Fixed tickets | #326 
Closes #326.
> fix: asset deduplication join updated to Pimcore 10 API

- src/DataDefinitionsBundle/Provider/AbstractFileProvider.php
- src/DataDefinitionsBundle/Provider/CsvProvider.php
- src/DataDefinitionsBundle/Provider/ExcelProvider.php
- src/DataDefinitionsBundle/Provider/JsonProvider.php
- src/DataDefinitionsBundle/Provider/XmlProvider.php
> feat: allow passing asset paths to import

- src/DataDefinitionsBundle/DependencyInjection/DataDefinitionsExtension.php
- src/DataDefinitionsBundle/Resources/config/guzzle_psr7.yml
> fix: auto-wire Guzzle PSR-7 if installed (which it is with Pimcore 10)

- src/DataDefinitionsBundle/Filter/FilterInterface.php
- src/DataDefinitionsBundle/Importer/Importer.php
> add params to filter

- src/DataDefinitionsBundle/Importer/Importer.php
- src/DataDefinitionsBundle/Runner/ImportStartFinishRunnerInterface.php
> Introduce Start-Finish Runner for start and end of an import

- src/DataDefinitionsBundle/Provider/AbstractFileProvider.php
- src/DataDefinitionsBundle/Resources/config/services.yml
- src/DataDefinitionsBundle/Service/StorageLocator.php
> allow to read import files from all storages

- src/DataDefinitionsBundle/Interpreter/CoreShop/CurrencyInterpreter.php
- src/DataDefinitionsBundle/Interpreter/CoreShop/MoneyInterpreter.php
- src/DataDefinitionsBundle/Interpreter/CoreShop/PriceInterpreter.php
- src/DataDefinitionsBundle/Interpreter/CoreShop/StoresInterpreter.php
> fix coreshop interpreter

- src/DataDefinitionsBundle/Importer/Importer.php
Counting might be expensive, doing it twice doesn't make sense
> fix: don't double-count the import file

- src/DataDefinitionsBundle/Interpreter/AssetsUrlInterpreter.php
> fix: correctly pass context to asset URL interpreter
